### ISSUE TITLE
Audio isn't working

### ISSUE THREAD

**Issue by edpgcooper** [motecshine/MSI-Z490A-PRO-i9-10850K-Hackintosh#2]
I'm running an Intel i5, Monterey 12.5
I updated PlatformInfo/Generic with an iMac20,1 profile to better suit my i5.  Any ideas what might be wrong?
Also what version of OpenCore is this config built on?

**Comment by motecshine** [comment]
Hi, What is the specific model of the sound card hardware？ 
maybe AppALC wiki can help you 
https://github.com/acidanthera/AppleALC/wiki/Supported-codecs

**Comment by edpgcooper** [comment]
**boot-args** _alcid=12_ got it working on the motherboard port for me, thanks.

**Comment by edpgcooper** [comment]
Its whatever is on the MSI-Z490-A PRO.  I don’t actually need audio for my application, just thought I should let you know.
Thanks

From: NOMAD ***@***.***>
Reply to: motecshine/MSI-Z490A-PRO-i9-10850K-Hackintosh ***@***.***>
Date: Tuesday, 16 August 2022 at 02:27
To: motecshine/MSI-Z490A-PRO-i9-10850K-Hackintosh ***@***.***>
Cc: Ed Cooper ***@***.***>, Author ***@***.***>
Subject: Re: [motecshine/MSI-Z490A-PRO-i9-10850K-Hackintosh] Audio isn't working (Issue #2)


Hi, What is the specific model of the sound card hardware？
maybe AppALC wiki can help you
https://github.com/acidanthera/AppleALC/wiki/Supported-codecs<https://protect-eu.mimecast.com/s/R0r7CnzxAsXK2Kc9SJ23?domain=github.com>
